** Meta
#+begin_src elisp
;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets.
(setq user-full-name "Justin Thong"
      user-mail-address "justinthong93@gmail.com")
#+end_src

** Font
#+begin_src elisp
;; Doom exposes five (optional) variables for controlling fonts in Doom. Here
;; are the three important ones:
;;
;; + `doom-font'
;; + `doom-variable-pitch-font'
;; + `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;;
;; They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
;; font string. You generally only need these two:
(setq doom-font (font-spec :family "Source Code Pro" :size 12 :weight 'semi-light)
      ;; doom-variable-pitch-font (font-spec :family "sans" :size 13)
      )
#+end_src

** Theme
#+begin_src elisp
;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
(setq doom-theme 'modus-vivendi)
;; Remove default hover highlight that removes ability to see syntax highlighting
;; (custom-set-faces! '((hl-line solaire-hl-line-face) :foreground nil))
#+end_src

** Org Mode
#+begin_src elisp
;; If you use `org' and don't want your org files in the default location below,
;; change `org-directory'. It must be set before org loads!
(setq org-directory "~/org/")
(setq org-roam-directory "~/org/roam/")
#+end_src

** Projectile Mode
#+begin_src elisp
(setq projectile-project-search-path '("~/Documents/GitHub/"))
#+end_src

** Dired
This keybinding is already taken by`SPC o -`
#+begin_src elisp
(use-package dired
  :commands (dired dired-jump)
  :bind (("C-x C-j" . dired-jump))
  :config
  (evil-collection-define-key 'normal 'dired-mode-map
   "H" 'dired-up-directory
   "L" 'dired-find-file
   )
  )
#+end_src

** Vim
#+begin_src elisp
;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'
(setq display-line-numbers-type 'relative)
#+end_src

** Javascript
I don't think require is needed because packages.el loads the packages already
#+begin_src elisp
(require 'prettier-js)
(add-hook 'js2-mode-hook 'prettier-js-mode)
(map! :leader
      :desc "Prettify" "m f" #'prettier-js
      )
#+end_src

** Selection
This helps me expand and contract selection
#+begin_src elisp
(map! :leader
      :desc "Expand region" "v" #'er/expand-region
      )
#+end_src

** Misc
#+begin_src elisp

(display-time-mode 1)
;; (if (eq initial-window-system 'x)                 ; if started by emacs command or desktop file
;;     (toggle-frame-maximized)
;;   (toggle-frame-fullscreen))

(global-set-key (kbd "<escape>") 'keyboard-escape-quit)

#+end_src

** Haskell
Again require might not be needed.`lsp-haskell` comes with the original init tag. Note: sometimes have to restart the server. hie file is not needed.
#+begin_src elisp
;; (require 'lsp)
;; (require 'lsp-haskell)
;; (add-hook 'haskell-mode-hook #'lsp)
;; (add-hook 'haskell-literate-mode-hook #'lsp)
(setq haskell-stylish-on-save nil)
(map! :leader
      (:after lsp-mode
       (:prefix ("l" . "LSP")
          :desc "Restart LSP server" "r" #'lsp-workspace-restart
          :desc "Excute code action" "a" #'lsp-execute-code-action
          :desc "Go to definition" "d" #'lsp-find-definition
          :desc "Toggle doc mode" "d" #'lsp-ui-doc-mode
          (:prefix ("u" . "LSP UI")
            :desc "Toggle doc mode" "d" #'lsp-ui-doc-mode
            :desc "Toggle sideline mode"  "s" #'lsp-ui-sideline-mode
            :desc "Glance at doc" "g" #'lsp-ui-doc-glance
            :desc "Toggle imenu"  "i" #'lsp-ui-imenu
            )
          )))
#+end_src

** LSP
These are generic settings for all languages but given you only use haskell.
#+begin_src elisp
(after! lsp-ui
  (setq lsp-ui-doc-enable t
        lsp-ui-doc-glance 1
        lsp-ui-doc-delay 0.5
        lsp-ui-doc-include-signature t
        lsp-ui-doc-position 'at-point
        lsp-ui-doc-border "#fdf5b1"
        lsp-ui-doc-max-width 65
        lsp-ui-doc-max-height 70
        lsp-ui-sideline-enable t
        lsp-ui-sideline-ignore-duplicate t
        lsp-ui-peek-enable t
        lsp-ui-flycheck-enable -1)

  (add-to-list 'lsp-ui-doc-frame-parameters '(left-fringe . 0))
)
#+end_src

** Presentation
I still don't know how to start presentation at a particular place.
#+begin_src elisp
(defun efs/presentation-setup ()
  (hide-mode-line-mode 1)
  (org-display-inline-images)
  (setq text-scale-mode-amount 3)
  (text-scale-mode 1)
  )
(defun efs/presentation-end ()
  (hide-mode-line-mode 0)
  (text-scale-mode 0)
  )
(use-package org-tree-slide
  :hook (
         (org-tree-slide-play . efs/presentation-setup)
         (org-tree-slide-stop . efs/presentation-end)
         )
  :custom
  (org-tree-slide-slide-in-effect t)
  (org-tree-slide-activate-message t)
  (org-tree-slide-deactivate-message t)
  (org-tree-slide-header t)
  (org-tree-slide-skip-comments 'nil)
)
#+end_src

** Command Log Mode
use-package is a reliable way to load packages with certain configs.
#+begin_src elisp
(use-package command-log-mode
  :config
  (global-command-log-mode)
  )
(setq command-log-mode-window-font-size 5)
#+end_src

** Indentation Formatting

#+begin_src elisp
(setq whitespace-mode 't)
#+end_src

** Org roam
Make sure you follow instruction [[github:org-roam/org-roam-server][org-roam-server]]
#+begin_src elisp
;; Interactive Org Roam Server Graph
;; (require 'simple-httpd)
;; (setq httpd-root "/var/www")
;; (httpd-start)
(require 'org-roam-protocol)
(use-package org-roam-server
  :ensure t
  :config
  (setq org-roam-server-host "127.0.0.1"
        org-roam-server-port 8080
        org-roam-server-authenticate nil
        org-roam-server-export-inline-images t
        org-roam-server-serve-files nil
        org-roam-server-served-file-extensions '("pdf" "mp4" "ogv")
        org-roam-server-network-poll t
        org-roam-server-network-arrows nil
        org-roam-server-network-label-truncate t
        org-roam-server-network-label-truncate-length 60
        org-roam-server-network-label-wrap-length 20))
#+end_src

** Lessons in Keybindings

#+begin_src elisp
(map! :leader
      :desc "test random prefix"
      "a j j" #'org-tree-slide-skip-comments-toggle)

(map! :leader
      (:prefix-map ("t" . "toggle")
       (:prefix ("s" . "tree-slide")
        :desc "Skip comments in slide" "c" #'org-tree-slide-skip-comments-toggle
        )
       )
      )
#+end_src

** Tiny

This helps us build linear ranges

** Key chording for normal mode
Just trying it out ppl say its good
#+begin_src elisp
(key-chord-mode 1)
(key-chord-define-global "jk" 'evil-normal-state)
#+end_src

** Electric Pairing for parentheses
Fix this later
;; #+begin_src elisp
 ;; (defun electric-pair ()
;;     "If at end of line, insert character pair without surrounding spaces.
;; Otherwise, just insert the typed character."
;;     (interactive)
;;     (if (eolp) (let (parens-require-spaces) (insert-pair)) (self-insert-command 1)))
;; (add-hook 'python-mode-hook
;;             (lambda ()
;;             (define-key python-mode-map "\"" 'electric-pair)
;;             (define-key python-mode-map "\'" 'electric-pair)
;;             (define-key python-mode-map "(" 'electric-pair)
;;             (define-key python-mode-map "[" 'electric-pair)
;;             (define-key python-mode-map "{" 'electric-pair)))
;; (add-hook js-mode-hook
;;             (lambda ()
;;             (define-key js-mode-map "(" 'electric-pair)
;;             (define-key js-mode-map "[" 'electric-pair)
;;             (define-key js-mode-map "{" 'electric-pair)))
;; #+end_src
** Eshell or Terminals
https://www.reddit.com/r/emacs/comments/b6n3t8/what_would_it_take_to_get_terminal_colors_in/
#+begin_src elisp
(add-hook 'eshell-mode-hook
          (lambda ()
            (setenv "TERM" "xterm-256color")))
(add-hook 'eshell-before-prompt-hook (setq xterm-color-preserve-properties t))
(add-to-list 'eshell-preoutput-filter-functions 'xterm-color-filter)
(setq eshell-output-filter-functions
     (remove 'eshell-handle-ansi-color eshell-output-filter-functions))
#+end_src
